#!/usr/bin/python

## This is a simple python script to create an empty file and copy it to the cert request directory for processing by the radius server.

import os
import subprocess
import pipes

def exists_remote(host, path):
    #Test if the request made it to the proper directory
    status = subprocess.call(
            ['ssh', host, 'test -f {}'.format(pipes.quote(path))])
    if status == 0:
        return True
    if status == 1:
        return False
    raise Exception('SSH failed')

name = input("What is the name of the machine?  ") # First we need the machine name

print("Creating certificate request for " + name)

os.system("touch /tmp/" + name) # This creates the request locally

os.system("scp /tmp/" + name + " root@10.14.0.20:/media/nss/VOL1/shared/madhs01rad1/requests/") # This copies the local file to the proper directory on the server

if exists_remote('root@10.14.0.20', '"/media/nss/VOL1/shared/madhs01rad1/requests/" + name'): 
    print("Certificate request generated successfully!")
else:
    print("Error")
